# Generated by Django 3.1.6 on 2021-02-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isopen',
            field=models.BooleanField(default=True),
        ),
    ]
